# ============================================
# store-gateway 启动配置
# ============================================

server:
  port: 18080

spring:
  application:
    name: store-gateway
  profiles:
    active: dev
  config:
    import: optional:nacos:store-gateway.yml?namespace=6fcc6887-5cdd-47d0-aece-6387e527b368
  autoconfigure:
    exclude:
      - org.springframework.cloud.client.discovery.simple.reactive.SimpleReactiveDiscoveryClientAutoConfiguration
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        namespace: 6fcc6887-5cdd-47d0-aece-6387e527b368
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: false
      metrics:
        enabled: true
      routes:
        - id: store-user-api
          uri: lb://store-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: store-goods-api
          uri: lb://store-goods
          predicates:
            - Path=/api/goods/**
          filters:
            - StripPrefix=1
