# ============================================
# store-gateway prod 环境配置
# ============================================

spring:
  cloud:
    nacos:
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
      server-addr: ${NACOS_SERVER}
