# ============================================
# saas-goods dev 环境配置
# ============================================

spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 127.0.0.1:8848
      config:
        namespace: 6fcc6887-5cdd-47d0-aece-6387e527b368
        shared-configs:
          - data-id: common.yml
            group: DEFAULT_GROUP
            refresh: true
      discovery:
        namespace: 6fcc6887-5cdd-47d0-aece-6387e527b368

# 启用 Feign Sentinel 降级
feign:
  sentinel:
    enabled: true

# Sentinel 基础配置（仅用于服务监控，可选）
sentinel:
  transport:
    port: 8719
