# ============================================
# account-gateway prod 环境配置
# ============================================

server:
  port: 18080

spring:
  application:
    name: account-gateway
  config:
    import: optional:nacos:common-jwt.yml,optional:nacos:account-gateway.yml
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  cloud:
    nacos:
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
      server-addr: ${NACOS_SERVER}
      config:
        namespace: 69ccd4d5-5392-4b12-8d8b-bae0e5039e18
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false
      discovery:
        namespace: 69ccd4d5-5392-4b12-8d8b-bae0e5039e18
        group: DEFAULT_GROUP
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: auth-api
          uri: lb://saas-auth
          predicates:
            - Path=/api/saas-auth/**
          filters:
            - StripPrefix=2
        - id: goods-api
          uri: lb://saas-goods
          predicates:
            - Path=/api/saas-goods/**
          filters:
            - StripPrefix=2
        - id: openapi-auth
          uri: lb://saas-auth
          predicates:
            - Path=/openapi/**
          filters:
            - StripPrefix=1

# OpenAPI配置
openapi:
  signature-expire-seconds: 300
  access-log:
    path: /data/logs/gateway
