# ============================================
# store-gateway 启动配置
# ============================================

server:
  port: 18080

spring:
  application:
    name: store-gateway
  profiles:
    active: dev
  config:
    import: optional:nacos:store-gateway.yml?namespace=6fcc6887-5cdd-47d0-aece-6387e527b368
  autoconfigure:
    exclude:
      - org.springframework.cloud.client.discovery.simple.reactive.SimpleReactiveDiscoveryClientAutoConfiguration
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
        namespace: 6fcc6887-5cdd-47d0-aece-6387e527b368
        group: DEFAULT_GROUP
        file-extension: yml
      discovery:
        namespace: 6fcc6887-5cdd-47d0-aece-6387e527b368
        group: DEFAULT_GROUP
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: false
      metrics:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,gateway,info,metrics
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
