# ============================================
# lzlj-auth dev 环境配置
# ============================================

server:
  port: 9294

spring:
  application:
    name: lzlj-auth
  config:
    import: optional:nacos:common.yml,optional:nacos:common-jwt.yml,optional:nacos:lzlj-auth.yml
  autoconfigure:
    exclude:
      - io.seata.spring.boot.autoconfigure.SeataAutoConfiguration
      - io.seata.spring.boot.autoconfigure.SeataCoreAutoConfiguration
      - io.seata.spring.boot.autoconfigure.SeataDataSourceAutoConfiguration
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 127.0.0.1:8848
      config:
        namespace: 6fcc6887-5cdd-47d0-aece-6387e527b368
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false
      discovery:
        namespace: 6fcc6887-5cdd-47d0-aece-6387e527b368
        group: DEFAULT_GROUP
