# ============================================
# account-auth 公共配置
# ============================================

spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
