# ============================================
# account-gateway dev 环境配置
# ============================================

spring:
  application:
    name: lzlj-gateway
  config:
    import: optional:nacos:common-jwt.yml,optional:nacos:lzlj-gateway.yml
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 127.0.0.1:8848
      config:
        namespace: 6fcc6887-5cdd-47d0-aece-6387e527b368
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false
      discovery:
        namespace: 6fcc6887-5cdd-47d0-aece-6387e527b368
        group: DEFAULT_GROUP
    gateway:
      routes:
        - id: auth-api
          uri: lb://lzlj-auth
          predicates:
            - Path=/api/lzlj-auth/**
          filters:
            - StripPrefix=2

# Swagger 聚合服务配置
swagger:
  services: lzlj-auth

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
