# ============================================
# saas-auth prod 环境配置
# ============================================

server:
  port: 9092

spring:
  application:
    name: saas-auth
  config:
    import: optional:nacos:common.yml,optional:nacos:common-jwt.yml,optional:nacos:saas-auth.yml
  autoconfigure:
    exclude:
      - io.seata.spring.boot.autoconfigure.SeataAutoConfiguration
      - io.seata.spring.boot.autoconfigure.SeataCoreAutoConfiguration
      - io.seata.spring.boot.autoconfigure.SeataDataSourceAutoConfiguration
  cloud:
    nacos:
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
      server-addr: ${NACOS_SERVER}
      config:
        namespace: 69ccd4d5-5392-4b12-8d8b-bae0e5039e18
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false
      discovery:
        namespace: 69ccd4d5-5392-4b12-8d8b-bae0e5039e18
        group: DEFAULT_GROUP
