# ============================================
# saas-auth dev 环境配置
# ============================================

server:
  port: 9092

spring:
  application:
    name: saas-auth
  config:
    import: optional:nacos:common.yml,optional:nacos:common-jwt.yml,optional:nacos:saas-auth.yml
  autoconfigure:
    exclude:
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 127.0.0.1:8848
      config:
        namespace: 6fcc6887-5cdd-47d0-aece-6387e527b368
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false
      discovery:
        namespace: 6fcc6887-5cdd-47d0-aece-6387e527b368
        group: DEFAULT_GROUP

# Springdoc OpenAPI 配置（解决 Swagger UI 默认显示 Petstore 的问题）
springdoc:
  swagger-ui:
    enabled: true
    url: /v3/api-docs
  api-docs:
    enabled: true
